### ISSUE TITLE
Azure AD Device Missing

### ISSUE THREAD

**Issue by rj-int** [niklasrast/Azure-Graph-Reporting#4]
Firstly this tool is fantastic!

I have granted all the necessary permissions to the app registration but for some reason when I run the script I am always left without the Azure AD Devices tab. any ideas where I can check?

**Comment by niklasrast** [comment]
Hey, I would recommend you to try running the function seperate without the Excel export, then you will see results listed on your console window. To do so you first need to initialize the variables like this:

$appId = "<PLACE-YOUR-DETAILS-HERE>"
$appSecret = "<PLACE-YOUR-DETAILS-HERE>"
$Customer = "<PLACE-YOUR-DETAILS-HERE>"
$ReportRecipient = "<PLACE-YOUR-DETAILS-HERE>"
$tenantId = "<PLACE-YOUR-DETAILS-HERE>"

once you have this import the part from the script where you authenticate to Entra ID with the AAD Token, which uses the variables to connect to your environment:

#Azure login token
$resourceAppIdUri = 'https://graph.microsoft.com'
$oAuthUri = "https://login.microsoftonline.com/$TenantId/oauth2/token"
$body = [Ordered] @{
    resource = "$resourceAppIdUri"
    client_id = "$appId"
    client_secret = "$appSecret"
    grant_type = 'client_credentials'
}
$response = Invoke-RestMethod -Method Post -Uri $oAuthUri -Body $body -ErrorAction Stop
$aadToken = $response.access_token

And now we are ready to run the "AzureADDevices" function manually, therefore you can run this code:

$url = "https://graph.microsoft.com/v1.0/deviceManagement/managedDevices"

# Set the WebRequest headers
$headers = @{
    'Content-Type' = 'application/json'
    Accept = 'application/json'
    Authorization = "Bearer $aadToken"
}

# Send the webrequest and get the results. 
$response = Invoke-WebRequest -Method Get -Uri $url -Headers $headers -ErrorAction Stop
#Extract the alerts from the results. 
$AADDevices = ($response | ConvertFrom-Json).value | ConvertTo-Json

foreach ($item in ($AADDevices | ConvertFrom-Json) ) {
    $AADDevice = [PSCustomObject]@{
        SerialNumber = $item.serialNumber
        DeviceName = $item.deviceName
        OperatingSystem = $item.operatingSystem
        Version = $item.osVersion
        Manufacturer = $item.manufacturer
        Model = $item.model
        PrimaryUser = $item.emailAddress
        LastIntuneSync = $item.lastSyncDateTime
     }
$AADDevice
}

This will either print the results on the console or display the error message why it is failing.
Optionally you could try to put an Transcript around the script but I had the most quickest troubleshooting with running the code this way to identify issues - mosten times they related on changes from Microsoft. 

I tried the code in my environment and there it worked yesterday. Maybe your environment is on another patch level?

**Comment by rj-int** [comment]
completely my bad, I had missed a permission. Not enough coffee after returning from holiday!

**Comment by rj-int** [comment]
completely my bad, I had missed a permission. Not enough coffee after returning from holiday!

**Comment by niklasrast** [comment]
Great that it then works :)
